# DEV
@BASE_URL=http://localhost:8080/school

###

# Hello World
POST {{BASE_URL}}/api/v1/auth
Accept: application/json
Content-Type: application/json

{
  "name": "Anas Juwaidi"
}

###

# Sign In
POST {{BASE_URL}}/api/v1/auth/sign-in
Accept: application/json
Content-Type: application/json

{
  "username": "anas.didi95",
  "password": "p@ssw0rd"
}
