# DEV
@BASE_URL=http://localhost:8080
@TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmFzLmRpZGk5NSIsIm5iZiI6MTc2NTg1NzQ3NCwicm9sZXMiOlsiU1VQRVJBRE1JTiJdLCJpc3MiOiJzY2hvb2wiLCJleHAiOjE3NjU4NjEwNzQsIl9fdXNlcklkIjoiNDRjNDlmZmYtZWRjNC00MmE0LTkwZDUtNDQ5ZDgzZDAyYjZmIiwiaWF0IjoxNzY1ODU3NDc0fQ.PK_ObiCnuj1fhRNJHuOCPTR1YVx1jgrrgWZva6_N9Ko

###

# Sign In
POST {{BASE_URL}}/api/v1/auth/sign-in
Accept: application/json
Content-Type: application/json

{
  "username": "anas.didi95",
  "password": "p@ssw0rd"
}

###

# Refresh Token
POST {{BASE_URL}}/api/v1/auth/refresh-token
Accept: application/json
Content-Type: application/json

{
  "jwt": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmFzLmRpZGk5NSIsIm5iZiI6MTc1OTY0NTQyNCwicm9sZXMiOlsiU1VQRVJBRE1JTiJdLCJpc3MiOiJzY2hvb2wiLCJleHAiOjE3NTk2NDkwMjQsIl9fdXNlcklkIjoiNDRjNDlmZmYtZWRjNC00MmE0LTkwZDUtNDQ5ZDgzZDAyYjZmIiwiaWF0IjoxNzU5NjQ1NDI0fQ.SzUHoQEmMjvJEDXJhAx0ZWOrAq8bYXJZ207d_Z8f4kQ",
  "refreshToken": "$2a$10$1D2UwoZdepBleCr8Ahmqtu1hfiMRZs.YeH2MWbny5r.Xws86orzBK"
}

###

# Sign Out
GET {{BASE_URL}}/api/v1/auth/sign-out
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###

# Token Info
GET {{BASE_URL}}/api/v1/auth/token-info
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
