# DEV
@BASE_URL=http://localhost:8080/school

###

# Hello World
POST {{BASE_URL}}/api/v1/auth
Accept: application/json
Content-Type: application/json

{
  "name": "Anas Juwaidi"
}

###

# Sign In
POST {{BASE_URL}}/api/v1/auth/sign-in
Accept: application/json
Content-Type: application/json

{
  "username": "anas.didi95",
  "password": "p@ssw0rd"
}

###

# Refresh Token
POST {{BASE_URL}}/api/v1/auth/refresh-token
Accept: application/json
Content-Type: application/json

{
  "username": "anas.didi95",
  "refreshToken": "$2a$10$H3wAUadogNG9/2qgV5rjJOEMJv7ZsvUSEgI1a84hVSm0YV/GjtXzW"
}

###

# Sign Out
GET {{BASE_URL}}/api/v1/auth/sign-out
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzY2hvb2wiLCJzdWIiOiJhbmFzLmRpZGk5NSIsIm5iZiI6MTc1OTI0MjU1MCwiZXhwIjoxNzU5MjQ2MTUwLCJpYXQiOjE3NTkyNDI1NTAsInJvbGVzIjpbXX0.8S3-Qbf78skXha7Ns9sUDyDPdpThFWS2Dr_QusOs1aU
