# DEV
@BASE_URL=http://localhost:8080
@TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmFzLmRpZGk5NSIsIm5iZiI6MTc2MDg0OTA0OCwicm9sZXMiOlsiU1VQRVJBRE1JTiJdLCJpc3MiOiJzY2hvb2wiLCJleHAiOjE3NjA4NTI2NDgsIl9fdXNlcklkIjoiNDRjNDlmZmYtZWRjNC00MmE0LTkwZDUtNDQ5ZDgzZDAyYjZmIiwiaWF0IjoxNzYwODQ5MDQ4fQ.0GDjBliB_BwkW1IRABp8LkLFEDT9vDoL4SdFawBY0MI

###

# Hello World
POST {{BASE_URL}}/api/v1/timesheet/helloWorld
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "name": "test"
}
