
# DEV
@BASE_URL=http://localhost:8080/school

###

# Add User
POST {{BASE_URL}}/api/v1/user
Accept: application/json
Content-Type: application/json

{
  "username": "test",
  "password": "p@ssw0rd",
  "name": "test"
}

###

# Search User
GET {{BASE_URL}}/api/v1/user?pageNo=1&name=
Accept: application/json
Content-Type: application/json
