---
services:
  app:
    command: "sleep infinity"
    image: "mcr.microsoft.com/devcontainers/java:1-21-bullseye"
    logging:
      driver: "local"
    volumes:
      - "./:/home/vscode/workspace/:z"
      - ".cache/.gradle/:/home/vscode/.gradle/:z"
