---
application:
  AUTH_RFH_TKN:
    refreshTokenExpiredSecs: "${APP_REFRESH_TOKEN_EXPIRY_SEC}"
    refreshTokenLeewaySecs: "${APP_REFRESH_TOKEN_LEEWAY_SEC}"
    refreshTokenRevokedSecs: "${APP_REFRESH_TOKEN_REVOKE_SEC}"
datasources:
  CN-AUTH:
    password: "${DB_AUTH_PWD}"
    url: "${DB_AUTH_URL}"
    username: "${DB_AUTH_USR}"
  CN-RBAC:
    password: "${DB_RBAC_PWD}"
    url: "${DB_RBAC_URL}"
    username: "${DB_RBAC_USR}"
  CN-TIMESHEET:
    password: "${DB_TIMESHEET_PWD}"
    url: "${DB_TIMESHEET_URL}"
    username: "${DB_TIMESHEET_USR}"
  CN-USER:
    password: "${DB_USER_PWD}"
    url: "${DB_USER_URL}"
    username: "${DB_USER_USR}"
liquibase:
  datasources:
    CN-AUTH:
      contexts: "prod"
    CN-RBAC:
      contexts: "prod"
    CN-TIMESHEET:
      contexts: "prod"
    CN-USER:
      contexts: "prod"
logger:
  levels:
    com.anasdidi.school: "${LOG_LEVEL}"
micronaut:
  router:
    static-resources:
      swagger:
        enabled: "${APP_SWAGGER_ENABLED}"
      swagger-ui:
        enabled: "${APP_SWAGGER_ENABLED}"
      web:
        enabled: "${APP_WEB_ENABLED}"
        paths: "file:/home/app/dist/"
  security:
    token:
      generator:
        access-token:
          expiration: "${JWT_EXPIRY_SEC}"
      jwt:
        signatures:
          secret:
            generator:
              secret: "${JWT_SECRET}"
