---
application:
  AUTH_RFH_TKN:
    refreshTokenExpiredSecs: 86400
    refreshTokenLeewaySecs: 30
    refreshTokenRevokedSecs: 3600
datasources:
  CN-AUTH:
    password: "sa"
    url: "jdbc:h2:./.h2/DB_SCHOOL_AUTH;AUTO_SERVER=TRUE"
    username: "sa"
  CN-RBAC:
    password: "sa"
    url: "jdbc:h2:./.h2/DB_SCHOOL_RBAC;AUTO_SERVER=TRUE"
    username: "sa"
  CN-TIMESHEET:
    password: "sa"
    url: "jdbc:h2:./.h2/DB_SCHOOL_TIMESHEET;AUTO_SERVER=TRUE"
    username: "sa"
  CN-USER:
    password: "sa"
    url: "jdbc:h2:./.h2/DB_SCHOOL_USER;AUTO_SERVER=TRUE"
    username: "sa"
jackson:
  json-view:
    enabled: true
jpa:
  default:
    compile-time-hibernate-proxies: true
    properties:
      hibernate:
        hbm2ddl.auto: "none"
        physical_naming_strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
liquibase:
  datasources:
    CN-AUTH:
      change-log: "classpath:db/db.changelog-auth.xml"
      contexts: "dev"
      enabled: true
    CN-RBAC:
      change-log: "classpath:db/db.changelog-rbac.xml"
      contexts: "dev"
      enabled: true
    CN-TIMESHEET:
      change-log: "classpath:db/db.changelog-timesheet.xml"
      contexts: "dev"
      enabled: true
    CN-USER:
      change-log: "classpath:db/db.changelog-user.xml"
      contexts: "dev"
      enabled: true
logger:
  levels:
    com.anasdidi.school: "TRACE"
    io.micronaut.management.health.aggregator.DefaultHealthAggregator: "TRACE"
micronaut:
  application:
    name: "school"
  router:
    static-resources:
      swagger:
        mapping: "/swagger/**"
        paths: "classpath:META-INF/swagger"
      swagger-ui:
        mapping: "/swagger-ui/**"
        paths: "classpath:META-INF/swagger/views/swagger-ui"
  security:
    intercept-url-map:
      # user
      - pattern: "/api/*/user/**"
        access: ["isAuthenticated()"]
      # auth
      - pattern: "/api/*/auth/sign-out"
        access: ["isAuthenticated()"]
      - pattern: "/api/*/auth/**"
        access: ["isAnonymous()"]
      # rbac
      - pattern: "/api/*/rbac/**"
        access: ["isAuthenticated()"]
      # timesheet
      - pattern: "/api/*/timesheet/**"
        access: ["isAuthenticated()"]
      # swagger
      - pattern: "/swagger/**"
        access: ["isAnonymous()"]
      - pattern: "/swagger-ui/**"
        access: ["isAnonymous()"]
    token:
      generator:
        access-token:
          expiration: 3600
      jwt:
        signatures:
          secret:
            generator:
              secret: "pleaseChangeThisSecretForANewOne"
  server:
    host: "0.0.0.0"
